package com.smartparking.global.error;

public enum ErrorCode {
    AUTH_TOKEN_INVALID,
    ACCESS_DENIED,
    PARKING_LOT_NOT_FOUND,
    PARKING_SPACE_NOT_FOUND,
    VERSION_CONFLICT,
    EMPTY_SPACE_CONFIRM_REQUIRED,
    DUPLICATE_SELECTION_CONFIRM_REQUIRED,
    VALIDATION_FAILED,
    CAMERA_STREAM_UNAVAILABLE,
    AI_SERVICE_UNAVAILABLE
}
